/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// MP2MPNetworkService
    /// </summary>
    [DataContract]
    public partial class MP2MPNetworkService : MP2MPNetworkServicePartial,  IEquatable<MP2MPNetworkService>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MP2MPNetworkService" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MP2MPNetworkService() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MP2MPNetworkService" /> class.
        /// </summary>
        /// <param name="billingAccount">An account requires billing_information to be used as a &#x60;billing_account&#x60;. (required).</param>
        /// <param name="chargedUntil">Your obligation to pay for the service will end on this date. Typically &#x60;≥ decommission_at&#x60;.  This field is only used when the state is &#x60;DECOMMISSION_REQUESTED&#x60; or &#x60;DECOMMISSIONED&#x60;..</param>
        /// <param name="consumingAccount">The &#x60;id&#x60; of the account consuming a service.  Used to be &#x60;owning_customer&#x60;.  (required).</param>
        /// <param name="contractRef">A reference to a contract. If no specific contract is used, a default MAY be chosen by the implementer. .</param>
        /// <param name="decommissionAt">The service will be decommissioned on this date.  This field is only used when the state is &#x60;DECOMMISSION_REQUESTED&#x60; or &#x60;DECOMMISSIONED&#x60;..</param>
        /// <param name="externalRef">Reference field, free to use for the API user..</param>
        /// <param name="id">id (required).</param>
        /// <param name="managingAccount">The &#x60;id&#x60; of the account responsible for managing the service via the API. A manager can read and update the state of entities.  (required).</param>
        /// <param name="memberJoiningRules">memberJoiningRules (required).</param>
        /// <param name="name">Name of the multi-point to multi-point virtual circuit. (required).</param>
        /// <param name="networkFeatures">networkFeatures (required).</param>
        /// <param name="productOffering">productOffering (required).</param>
        /// <param name="_public">A public mp2mp network service can be joined by everyone on the exchange unless denied by a member-joining-rule.  Public network services are visible to other members of the IXP, however only &#x60;name&#x60;, &#x60;type&#x60;, &#x60;product_offering&#x60;, &#x60;consuming_account&#x60; and &#x60;managing_account&#x60; are made available.  Other required fields are redacted. (default to false).</param>
        /// <param name="purchaseOrder">Purchase Order ID which will be displayed on the invoice.  (default to &quot;&quot;).</param>
        /// <param name="state">state (required).</param>
        /// <param name="status">status.</param>
        /// <param name="type">type (required).</param>
        public MP2MPNetworkService(string billingAccount = default(string), DateTime chargedUntil = default(DateTime), string consumingAccount = default(string), string contractRef = default(string), DateTime decommissionAt = default(DateTime), string externalRef = default(string), string id = default(string), string managingAccount = default(string), List<string> memberJoiningRules = default(List<string>), string name = default(string), List<string> networkFeatures = default(List<string>), string productOffering = default(string), bool _public = false, string purchaseOrder = "", StateEnum state = default(StateEnum), List<Status> status = default(List<Status>), string type = default(string)) : base(billingAccount, chargedUntil, consumingAccount, contractRef, decommissionAt, externalRef, id, managingAccount, memberJoiningRules, name, networkFeatures, nscRequiredContactRoles, productOffering, _public, purchaseOrder, state, status, type)
        {
        }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MP2MPNetworkService {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MP2MPNetworkService);
        }

        /// <summary>
        /// Returns true if MP2MPNetworkService instances are equal
        /// </summary>
        /// <param name="input">Instance of MP2MPNetworkService to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MP2MPNetworkService input)
        {
            if (input == null)
                return false;

            return base.Equals(input);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
