/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A Dot1Q vlan configuration
    /// </summary>
    [DataContract]
    public partial class VLanConfigDot1QPartial :  IEquatable<VLanConfigDot1QPartial>, IValidatableObject
    {
        /// <summary>
        /// The ethertype of the vlan in hexadecimal notation.
        /// </summary>
        /// <value>The ethertype of the vlan in hexadecimal notation.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VlanEthertypeEnum
        {
            /// <summary>
            /// Enum _0x8100 for value: 0x8100
            /// </summary>
            [EnumMember(Value = "0x8100")]
            _0x8100 = 1,

            /// <summary>
            /// Enum _0x88a8 for value: 0x88a8
            /// </summary>
            [EnumMember(Value = "0x88a8")]
            _0x88a8 = 2,

            /// <summary>
            /// Enum _0x9100 for value: 0x9100
            /// </summary>
            [EnumMember(Value = "0x9100")]
            _0x9100 = 3

        }

        /// <summary>
        /// The ethertype of the vlan in hexadecimal notation.
        /// </summary>
        /// <value>The ethertype of the vlan in hexadecimal notation.</value>
        [DataMember(Name="vlan_ethertype", EmitDefaultValue=false)]
        public VlanEthertypeEnum? VlanEthertype { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VLanConfigDot1QPartial" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VLanConfigDot1QPartial() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VLanConfigDot1QPartial" /> class.
        /// </summary>
        /// <param name="vlan">A VLAN tag. If &#x60;null&#x60;, the IXP will auto-select a valid vlan-id. .</param>
        /// <param name="vlanEthertype">The ethertype of the vlan in hexadecimal notation. (default to VlanEthertypeEnum._0x8100).</param>
        /// <param name="vlanType">vlanType (required).</param>
        public VLanConfigDot1QPartial(int? vlan = default(int?), VlanEthertypeEnum? vlanEthertype = VlanEthertypeEnum._0x8100, string vlanType = default(string))
        {
            // to ensure "vlanType" is required (not null)
            this.VlanType = vlanType ?? throw new ArgumentNullException("vlanType is a required property for VLanConfigDot1QPartial and cannot be null");
            this.Vlan = vlan;
            this.VlanEthertype = vlanEthertype;
        }
        
        /// <summary>
        /// A VLAN tag. If &#x60;null&#x60;, the IXP will auto-select a valid vlan-id. 
        /// </summary>
        /// <value>A VLAN tag. If &#x60;null&#x60;, the IXP will auto-select a valid vlan-id. </value>
        [DataMember(Name="vlan", EmitDefaultValue=true)]
        public int? Vlan { get; set; }

        /// <summary>
        /// Gets or Sets VlanType
        /// </summary>
        [DataMember(Name="vlan_type", EmitDefaultValue=false)]
        public string VlanType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VLanConfigDot1QPartial {\n");
            sb.Append("  Vlan: ").Append(Vlan).Append("\n");
            sb.Append("  VlanEthertype: ").Append(VlanEthertype).Append("\n");
            sb.Append("  VlanType: ").Append(VlanType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VLanConfigDot1QPartial);
        }

        /// <summary>
        /// Returns true if VLanConfigDot1QPartial instances are equal
        /// </summary>
        /// <param name="input">Instance of VLanConfigDot1QPartial to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VLanConfigDot1QPartial input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Vlan == input.Vlan ||
                    (this.Vlan != null &&
                    this.Vlan.Equals(input.Vlan))
                ) && 
                (
                    this.VlanEthertype == input.VlanEthertype ||
                    this.VlanEthertype.Equals(input.VlanEthertype)
                ) && 
                (
                    this.VlanType == input.VlanType ||
                    (this.VlanType != null &&
                    this.VlanType.Equals(input.VlanType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Vlan != null)
                    hashCode = hashCode * 59 + this.Vlan.GetHashCode();
                hashCode = hashCode * 59 + this.VlanEthertype.GetHashCode();
                if (this.VlanType != null)
                    hashCode = hashCode * 59 + this.VlanType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Vlan (int?) maximum
            if(this.Vlan > (int?)4094)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Vlan, must be a value less than or equal to 4094.", new [] { "Vlan" });
            }

            // Vlan (int?) minimum
            if(this.Vlan < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Vlan, must be a value greater than or equal to 1.", new [] { "Vlan" });
            }

            yield break;
        }
    }

}
