# coding: utf-8

"""
    IX-API

     This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error.   # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProblemResponsePartial(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'detail': 'str',
        'instance': 'str',
        'status': 'int',
        'title': 'str',
        'type': 'str'
    }

    attribute_map = {
        'detail': 'detail',
        'instance': 'instance',
        'status': 'status',
        'title': 'title',
        'type': 'type'
    }

    def __init__(self, detail=None, instance=None, status=None, title=None, type=None):  # noqa: E501
        """ProblemResponsePartial - a model defined in Swagger"""  # noqa: E501
        self._detail = None
        self._instance = None
        self._status = None
        self._title = None
        self._type = None
        self.discriminator = None
        if detail is not None:
            self.detail = detail
        if instance is not None:
            self.instance = instance
        if status is not None:
            self.status = status
        if title is not None:
            self.title = title
        if type is not None:
            self.type = type

    @property
    def detail(self):
        """Gets the detail of this ProblemResponsePartial.  # noqa: E501

        A human-readable explanation specific to this occurrence of the problem.  # noqa: E501

        :return: The detail of this ProblemResponsePartial.  # noqa: E501
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this ProblemResponsePartial.

        A human-readable explanation specific to this occurrence of the problem.  # noqa: E501

        :param detail: The detail of this ProblemResponsePartial.  # noqa: E501
        :type: str
        """

        self._detail = detail

    @property
    def instance(self):
        """Gets the instance of this ProblemResponsePartial.  # noqa: E501

        A URI reference that identifies the specific occurrence of the problem.  It may or may not yield further information if dereferenced.  # noqa: E501

        :return: The instance of this ProblemResponsePartial.  # noqa: E501
        :rtype: str
        """
        return self._instance

    @instance.setter
    def instance(self, instance):
        """Sets the instance of this ProblemResponsePartial.

        A URI reference that identifies the specific occurrence of the problem.  It may or may not yield further information if dereferenced.  # noqa: E501

        :param instance: The instance of this ProblemResponsePartial.  # noqa: E501
        :type: str
        """

        self._instance = instance

    @property
    def status(self):
        """Gets the status of this ProblemResponsePartial.  # noqa: E501

        The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.  # noqa: E501

        :return: The status of this ProblemResponsePartial.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ProblemResponsePartial.

        The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.  # noqa: E501

        :param status: The status of this ProblemResponsePartial.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def title(self):
        """Gets the title of this ProblemResponsePartial.  # noqa: E501

        A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section 3.4).   # noqa: E501

        :return: The title of this ProblemResponsePartial.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ProblemResponsePartial.

        A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section 3.4).   # noqa: E501

        :param title: The title of this ProblemResponsePartial.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def type(self):
        """Gets the type of this ProblemResponsePartial.  # noqa: E501

        A URI reference (see RFC3986) that identifies the problem type.  This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When this member is not present, its value is assumed to be \"about:blank\".   # noqa: E501

        :return: The type of this ProblemResponsePartial.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ProblemResponsePartial.

        A URI reference (see RFC3986) that identifies the problem type.  This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When this member is not present, its value is assumed to be \"about:blank\".   # noqa: E501

        :param type: The type of this ProblemResponsePartial.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProblemResponsePartial, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProblemResponsePartial):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
