# coding: utf-8

"""
    IX-API

     This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error.   # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StatusPartial(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attrs': 'object',
        'message': 'str',
        'severity': 'int',
        'tag': 'str',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'attrs': 'attrs',
        'message': 'message',
        'severity': 'severity',
        'tag': 'tag',
        'timestamp': 'timestamp'
    }

    def __init__(self, attrs=None, message=None, severity=None, tag=None, timestamp=None):  # noqa: E501
        """StatusPartial - a model defined in Swagger"""  # noqa: E501
        self._attrs = None
        self._message = None
        self._severity = None
        self._tag = None
        self._timestamp = None
        self.discriminator = None
        if attrs is not None:
            self.attrs = attrs
        if message is not None:
            self.message = message
        if severity is not None:
            self.severity = severity
        if tag is not None:
            self.tag = tag
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def attrs(self):
        """Gets the attrs of this StatusPartial.  # noqa: E501


        :return: The attrs of this StatusPartial.  # noqa: E501
        :rtype: object
        """
        return self._attrs

    @attrs.setter
    def attrs(self, attrs):
        """Sets the attrs of this StatusPartial.


        :param attrs: The attrs of this StatusPartial.  # noqa: E501
        :type: object
        """

        self._attrs = attrs

    @property
    def message(self):
        """Gets the message of this StatusPartial.  # noqa: E501


        :return: The message of this StatusPartial.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this StatusPartial.


        :param message: The message of this StatusPartial.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def severity(self):
        """Gets the severity of this StatusPartial.  # noqa: E501

        We are using syslog severity levels: 0 = Emergency, 1 = Alert, 2 = Critical, 3 = Error, 4 = Warning, 5 = Notice, 6 = Informational, 7 = Debug.   # noqa: E501

        :return: The severity of this StatusPartial.  # noqa: E501
        :rtype: int
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """Sets the severity of this StatusPartial.

        We are using syslog severity levels: 0 = Emergency, 1 = Alert, 2 = Critical, 3 = Error, 4 = Warning, 5 = Notice, 6 = Informational, 7 = Debug.   # noqa: E501

        :param severity: The severity of this StatusPartial.  # noqa: E501
        :type: int
        """

        self._severity = severity

    @property
    def tag(self):
        """Gets the tag of this StatusPartial.  # noqa: E501


        :return: The tag of this StatusPartial.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this StatusPartial.


        :param tag: The tag of this StatusPartial.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def timestamp(self):
        """Gets the timestamp of this StatusPartial.  # noqa: E501


        :return: The timestamp of this StatusPartial.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this StatusPartial.


        :param timestamp: The timestamp of this StatusPartial.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatusPartial, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatusPartial):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
