/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ExchangeLanNetworkServicePartial
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExchangeLanNetworkServicePartialTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExchangeLanNetworkServicePartial
        //private ExchangeLanNetworkServicePartial instance;

        public ExchangeLanNetworkServicePartialTests()
        {
            // TODO uncomment below to create an instance of ExchangeLanNetworkServicePartial
            //instance = new ExchangeLanNetworkServicePartial();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExchangeLanNetworkServicePartial
        /// </summary>
        [Fact]
        public void ExchangeLanNetworkServicePartialInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExchangeLanNetworkServicePartial
            //Assert.IsInstanceOfType<ExchangeLanNetworkServicePartial> (instance, "variable 'instance' is a ExchangeLanNetworkServicePartial");
        }


        /// <summary>
        /// Test the property 'ConsumingAccount'
        /// </summary>
        [Fact]
        public void ConsumingAccountTest()
        {
            // TODO unit test for the property 'ConsumingAccount'
        }
        /// <summary>
        /// Test the property 'ExternalRef'
        /// </summary>
        [Fact]
        public void ExternalRefTest()
        {
            // TODO unit test for the property 'ExternalRef'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IxfdbIxid'
        /// </summary>
        [Fact]
        public void IxfdbIxidTest()
        {
            // TODO unit test for the property 'IxfdbIxid'
        }
        /// <summary>
        /// Test the property 'ManagingAccount'
        /// </summary>
        [Fact]
        public void ManagingAccountTest()
        {
            // TODO unit test for the property 'ManagingAccount'
        }
        /// <summary>
        /// Test the property 'MetroAreaNetwork'
        /// </summary>
        [Fact]
        public void MetroAreaNetworkTest()
        {
            // TODO unit test for the property 'MetroAreaNetwork'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NetworkFeatures'
        /// </summary>
        [Fact]
        public void NetworkFeaturesTest()
        {
            // TODO unit test for the property 'NetworkFeatures'
        }
        /// <summary>
        /// Test the property 'NscRequiredContactRoles'
        /// </summary>
        [Fact]
        public void NscRequiredContactRolesTest()
        {
            // TODO unit test for the property 'NscRequiredContactRoles'
        }
        /// <summary>
        /// Test the property 'PeeringdbIxid'
        /// </summary>
        [Fact]
        public void PeeringdbIxidTest()
        {
            // TODO unit test for the property 'PeeringdbIxid'
        }
        /// <summary>
        /// Test the property 'ProductOffering'
        /// </summary>
        [Fact]
        public void ProductOfferingTest()
        {
            // TODO unit test for the property 'ProductOffering'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SubnetV4'
        /// </summary>
        [Fact]
        public void SubnetV4Test()
        {
            // TODO unit test for the property 'SubnetV4'
        }
        /// <summary>
        /// Test the property 'SubnetV6'
        /// </summary>
        [Fact]
        public void SubnetV6Test()
        {
            // TODO unit test for the property 'SubnetV6'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
