/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing P2MPNetworkServicePartial
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class P2MPNetworkServicePartialTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for P2MPNetworkServicePartial
        //private P2MPNetworkServicePartial instance;

        public P2MPNetworkServicePartialTests()
        {
            // TODO uncomment below to create an instance of P2MPNetworkServicePartial
            //instance = new P2MPNetworkServicePartial();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of P2MPNetworkServicePartial
        /// </summary>
        [Fact]
        public void P2MPNetworkServicePartialInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" P2MPNetworkServicePartial
            //Assert.IsInstanceOfType<P2MPNetworkServicePartial> (instance, "variable 'instance' is a P2MPNetworkServicePartial");
        }


        /// <summary>
        /// Test the property 'BillingAccount'
        /// </summary>
        [Fact]
        public void BillingAccountTest()
        {
            // TODO unit test for the property 'BillingAccount'
        }
        /// <summary>
        /// Test the property 'ChargedUntil'
        /// </summary>
        [Fact]
        public void ChargedUntilTest()
        {
            // TODO unit test for the property 'ChargedUntil'
        }
        /// <summary>
        /// Test the property 'ConsumingAccount'
        /// </summary>
        [Fact]
        public void ConsumingAccountTest()
        {
            // TODO unit test for the property 'ConsumingAccount'
        }
        /// <summary>
        /// Test the property 'ContractRef'
        /// </summary>
        [Fact]
        public void ContractRefTest()
        {
            // TODO unit test for the property 'ContractRef'
        }
        /// <summary>
        /// Test the property 'DecommissionAt'
        /// </summary>
        [Fact]
        public void DecommissionAtTest()
        {
            // TODO unit test for the property 'DecommissionAt'
        }
        /// <summary>
        /// Test the property 'ExternalRef'
        /// </summary>
        [Fact]
        public void ExternalRefTest()
        {
            // TODO unit test for the property 'ExternalRef'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ManagingAccount'
        /// </summary>
        [Fact]
        public void ManagingAccountTest()
        {
            // TODO unit test for the property 'ManagingAccount'
        }
        /// <summary>
        /// Test the property 'MemberJoiningRules'
        /// </summary>
        [Fact]
        public void MemberJoiningRulesTest()
        {
            // TODO unit test for the property 'MemberJoiningRules'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NetworkFeatures'
        /// </summary>
        [Fact]
        public void NetworkFeaturesTest()
        {
            // TODO unit test for the property 'NetworkFeatures'
        }
        /// <summary>
        /// Test the property 'NscRequiredContactRoles'
        /// </summary>
        [Fact]
        public void NscRequiredContactRolesTest()
        {
            // TODO unit test for the property 'NscRequiredContactRoles'
        }
        /// <summary>
        /// Test the property 'ProductOffering'
        /// </summary>
        [Fact]
        public void ProductOfferingTest()
        {
            // TODO unit test for the property 'ProductOffering'
        }
        /// <summary>
        /// Test the property 'Public'
        /// </summary>
        [Fact]
        public void PublicTest()
        {
            // TODO unit test for the property 'Public'
        }
        /// <summary>
        /// Test the property 'PurchaseOrder'
        /// </summary>
        [Fact]
        public void PurchaseOrderTest()
        {
            // TODO unit test for the property 'PurchaseOrder'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
