/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing P2PNetworkService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class P2PNetworkServiceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for P2PNetworkService
        //private P2PNetworkService instance;

        public P2PNetworkServiceTests()
        {
            // TODO uncomment below to create an instance of P2PNetworkService
            //instance = new P2PNetworkService();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of P2PNetworkService
        /// </summary>
        [Fact]
        public void P2PNetworkServiceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" P2PNetworkService
            //Assert.IsInstanceOfType<P2PNetworkService> (instance, "variable 'instance' is a P2PNetworkService");
        }



    }

}
