/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StatusPartial
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatusPartialTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StatusPartial
        //private StatusPartial instance;

        public StatusPartialTests()
        {
            // TODO uncomment below to create an instance of StatusPartial
            //instance = new StatusPartial();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StatusPartial
        /// </summary>
        [Fact]
        public void StatusPartialInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StatusPartial
            //Assert.IsInstanceOfType<StatusPartial> (instance, "variable 'instance' is a StatusPartial");
        }


        /// <summary>
        /// Test the property 'Attrs'
        /// </summary>
        [Fact]
        public void AttrsTest()
        {
            // TODO unit test for the property 'Attrs'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Fact]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

    }

}
