/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing VLanConfigDot1Q
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VLanConfigDot1QTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VLanConfigDot1Q
        //private VLanConfigDot1Q instance;

        public VLanConfigDot1QTests()
        {
            // TODO uncomment below to create an instance of VLanConfigDot1Q
            //instance = new VLanConfigDot1Q();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VLanConfigDot1Q
        /// </summary>
        [Fact]
        public void VLanConfigDot1QInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VLanConfigDot1Q
            //Assert.IsInstanceOfType<VLanConfigDot1Q> (instance, "variable 'instance' is a VLanConfigDot1Q");
        }



    }

}
