/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// P2PNetworkService
    /// </summary>
    [DataContract]
        public partial class P2PNetworkService : P2PNetworkServicePartial,  IEquatable<P2PNetworkService>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="P2PNetworkService" /> class.
        /// </summary>
        public P2PNetworkService(string billingAccount = default(string), int? capacity = default(int?), DateTime? chargedUntil = default(DateTime?), string consumingAccount = default(string), string contractRef = default(string), DateTime? decommissionAt = default(DateTime?), string externalRef = default(string), string id = default(string), string joiningMemberAccount = default(string), string managingAccount = default(string), string productOffering = default(string), string purchaseOrder = "", StateEnum state = default(StateEnum), List<Status> status = default(List<Status>), string type = default(string)) : base(billingAccount, capacity, chargedUntil, consumingAccount, contractRef, decommissionAt, externalRef, id, joiningMemberAccount, managingAccount, nscRequiredContactRoles, productOffering, purchaseOrder, state, status, type)
        {
        }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class P2PNetworkService {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as P2PNetworkService);
        }

        /// <summary>
        /// Returns true if P2PNetworkService instances are equal
        /// </summary>
        /// <param name="input">Instance of P2PNetworkService to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(P2PNetworkService input)
        {
            if (input == null)
                return false;

            return base.Equals(input);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
