/* 
 * IX-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DogAllOf
    /// </summary>
    [DataContract]
    public partial class DogAllOf :  IEquatable<DogAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DogAllOf" /> class.
        /// </summary>
        /// <param name="bark">bark.</param>
        public DogAllOf(string bark = default(string))
        {
            this.Bark = bark;
        }
        
        /// <summary>
        /// Gets or Sets Bark
        /// </summary>
        [DataMember(Name="bark", EmitDefaultValue=false)]
        public string Bark { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DogAllOf {\n");
            sb.Append("  Bark: ").Append(Bark).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DogAllOf);
        }

        /// <summary>
        /// Returns true if DogAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of DogAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DogAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Bark == input.Bark ||
                    (this.Bark != null &&
                    this.Bark.Equals(input.Bark))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Bark != null)
                    hashCode = hashCode * 59 + this.Bark.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
