/*
 * IX-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.DogAllOf;
import org.openapitools.client.model.Pet;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Dog
 */
public class DogTest {
    private final Dog model = new Dog();

    /**
     * Model tests for Dog
     */
    @Test
    public void testDog() {
        // TODO: test Dog
    }

    /**
     * Test the property 'petType'
     */
    @Test
    public void petTypeTest() {
        // TODO: test petType
    }

    /**
     * Test the property 'bark'
     */
    @Test
    public void barkTest() {
        // TODO: test bark
    }

}
