/*
 * IX-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.LizardAllOf;
import org.openapitools.client.model.Pet;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Lizard
 */
public class LizardTest {
    private final Lizard model = new Lizard();

    /**
     * Model tests for Lizard
     */
    @Test
    public void testLizard() {
        // TODO: test Lizard
    }

    /**
     * Test the property 'petType'
     */
    @Test
    public void petTypeTest() {
        // TODO: test petType
    }

    /**
     * Test the property 'lovesRocks'
     */
    @Test
    public void lovesRocksTest() {
        // TODO: test lovesRocks
    }

}
