/* 
 * IX-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CatAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CatAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CatAllOf
        //private CatAllOf instance;

        public CatAllOfTests()
        {
            // TODO uncomment below to create an instance of CatAllOf
            //instance = new CatAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CatAllOf
        /// </summary>
        [Fact]
        public void CatAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CatAllOf
            //Assert.IsInstanceOfType<CatAllOf> (instance, "variable 'instance' is a CatAllOf");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
