/* 
 * IX-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DogAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DogAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DogAllOf
        //private DogAllOf instance;

        public DogAllOfTests()
        {
            // TODO uncomment below to create an instance of DogAllOf
            //instance = new DogAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DogAllOf
        /// </summary>
        [Fact]
        public void DogAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DogAllOf
            //Assert.IsInstanceOfType<DogAllOf> (instance, "variable 'instance' is a DogAllOf");
        }


        /// <summary>
        /// Test the property 'Bark'
        /// </summary>
        [Fact]
        public void BarkTest()
        {
            // TODO unit test for the property 'Bark'
        }

    }

}
