/* 
 * IX-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing LizardAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LizardAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LizardAllOf
        //private LizardAllOf instance;

        public LizardAllOfTests()
        {
            // TODO uncomment below to create an instance of LizardAllOf
            //instance = new LizardAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LizardAllOf
        /// </summary>
        [Fact]
        public void LizardAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LizardAllOf
            //Assert.IsInstanceOfType<LizardAllOf> (instance, "variable 'instance' is a LizardAllOf");
        }


        /// <summary>
        /// Test the property 'LovesRocks'
        /// </summary>
        [Fact]
        public void LovesRocksTest()
        {
            // TODO unit test for the property 'LovesRocks'
        }

    }

}
