/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NetworkService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NetworkServiceTests
    {
        // TODO uncomment below to declare an instance variable for NetworkService
        //private NetworkService instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NetworkService
            //instance = new NetworkService();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NetworkService
        /// </summary>
        [Test]
        public void NetworkServiceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" NetworkService
            //Assert.IsInstanceOf(typeof(NetworkService), instance);
        }


        /// <summary>
        /// Test the property 'ConsumingAccount'
        /// </summary>
        [Test]
        public void ConsumingAccountTest()
        {
            // TODO unit test for the property 'ConsumingAccount'
        }
        /// <summary>
        /// Test the property 'ExternalRef'
        /// </summary>
        [Test]
        public void ExternalRefTest()
        {
            // TODO unit test for the property 'ExternalRef'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IxfdbIxid'
        /// </summary>
        [Test]
        public void IxfdbIxidTest()
        {
            // TODO unit test for the property 'IxfdbIxid'
        }
        /// <summary>
        /// Test the property 'ManagingAccount'
        /// </summary>
        [Test]
        public void ManagingAccountTest()
        {
            // TODO unit test for the property 'ManagingAccount'
        }
        /// <summary>
        /// Test the property 'MetroAreaNetwork'
        /// </summary>
        [Test]
        public void MetroAreaNetworkTest()
        {
            // TODO unit test for the property 'MetroAreaNetwork'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NetworkFeatures'
        /// </summary>
        [Test]
        public void NetworkFeaturesTest()
        {
            // TODO unit test for the property 'NetworkFeatures'
        }
        /// <summary>
        /// Test the property 'NscRequiredContactRoles'
        /// </summary>
        [Test]
        public void NscRequiredContactRolesTest()
        {
            // TODO unit test for the property 'NscRequiredContactRoles'
        }
        /// <summary>
        /// Test the property 'PeeringdbIxid'
        /// </summary>
        [Test]
        public void PeeringdbIxidTest()
        {
            // TODO unit test for the property 'PeeringdbIxid'
        }
        /// <summary>
        /// Test the property 'ProductOffering'
        /// </summary>
        [Test]
        public void ProductOfferingTest()
        {
            // TODO unit test for the property 'ProductOffering'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SubnetV4'
        /// </summary>
        [Test]
        public void SubnetV4Test()
        {
            // TODO unit test for the property 'SubnetV4'
        }
        /// <summary>
        /// Test the property 'SubnetV6'
        /// </summary>
        [Test]
        public void SubnetV6Test()
        {
            // TODO unit test for the property 'SubnetV6'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'BillingAccount'
        /// </summary>
        [Test]
        public void BillingAccountTest()
        {
            // TODO unit test for the property 'BillingAccount'
        }
        /// <summary>
        /// Test the property 'Capacity'
        /// </summary>
        [Test]
        public void CapacityTest()
        {
            // TODO unit test for the property 'Capacity'
        }
        /// <summary>
        /// Test the property 'ChargedUntil'
        /// </summary>
        [Test]
        public void ChargedUntilTest()
        {
            // TODO unit test for the property 'ChargedUntil'
        }
        /// <summary>
        /// Test the property 'ContractRef'
        /// </summary>
        [Test]
        public void ContractRefTest()
        {
            // TODO unit test for the property 'ContractRef'
        }
        /// <summary>
        /// Test the property 'DecommissionAt'
        /// </summary>
        [Test]
        public void DecommissionAtTest()
        {
            // TODO unit test for the property 'DecommissionAt'
        }
        /// <summary>
        /// Test the property 'JoiningMemberAccount'
        /// </summary>
        [Test]
        public void JoiningMemberAccountTest()
        {
            // TODO unit test for the property 'JoiningMemberAccount'
        }
        /// <summary>
        /// Test the property 'PurchaseOrder'
        /// </summary>
        [Test]
        public void PurchaseOrderTest()
        {
            // TODO unit test for the property 'PurchaseOrder'
        }
        /// <summary>
        /// Test the property 'MemberJoiningRules'
        /// </summary>
        [Test]
        public void MemberJoiningRulesTest()
        {
            // TODO unit test for the property 'MemberJoiningRules'
        }
        /// <summary>
        /// Test the property 'Public'
        /// </summary>
        [Test]
        public void PublicTest()
        {
            // TODO unit test for the property 'Public'
        }
        /// <summary>
        /// Test the property 'CloudKey'
        /// </summary>
        [Test]
        public void CloudKeyTest()
        {
            // TODO unit test for the property 'CloudKey'
        }
        /// <summary>
        /// Test the property 'Diversity'
        /// </summary>
        [Test]
        public void DiversityTest()
        {
            // TODO unit test for the property 'Diversity'
        }
        /// <summary>
        /// Test the property 'ProviderRef'
        /// </summary>
        [Test]
        public void ProviderRefTest()
        {
            // TODO unit test for the property 'ProviderRef'
        }

    }

}
