# coding: utf-8

# flake8: noqa

"""
    IX-API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.cat import Cat
from swagger_client.models.dog import Dog
from swagger_client.models.lizard import Lizard
from swagger_client.models.pet import Pet
