/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CloudNetworkServicePartial
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CloudNetworkServicePartialTests
    {
        // TODO uncomment below to declare an instance variable for CloudNetworkServicePartial
        //private CloudNetworkServicePartial instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CloudNetworkServicePartial
            //instance = new CloudNetworkServicePartial();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CloudNetworkServicePartial
        /// </summary>
        [Test]
        public void CloudNetworkServicePartialInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CloudNetworkServicePartial
            //Assert.IsInstanceOfType<CloudNetworkServicePartial> (instance, "variable 'instance' is a CloudNetworkServicePartial");
        }


        /// <summary>
        /// Test the property 'BillingAccount'
        /// </summary>
        [Test]
        public void BillingAccountTest()
        {
            // TODO unit test for the property 'BillingAccount'
        }
        /// <summary>
        /// Test the property 'Capacity'
        /// </summary>
        [Test]
        public void CapacityTest()
        {
            // TODO unit test for the property 'Capacity'
        }
        /// <summary>
        /// Test the property 'ChargedUntil'
        /// </summary>
        [Test]
        public void ChargedUntilTest()
        {
            // TODO unit test for the property 'ChargedUntil'
        }
        /// <summary>
        /// Test the property 'CloudKey'
        /// </summary>
        [Test]
        public void CloudKeyTest()
        {
            // TODO unit test for the property 'CloudKey'
        }
        /// <summary>
        /// Test the property 'ConsumingAccount'
        /// </summary>
        [Test]
        public void ConsumingAccountTest()
        {
            // TODO unit test for the property 'ConsumingAccount'
        }
        /// <summary>
        /// Test the property 'ContractRef'
        /// </summary>
        [Test]
        public void ContractRefTest()
        {
            // TODO unit test for the property 'ContractRef'
        }
        /// <summary>
        /// Test the property 'DecommissionAt'
        /// </summary>
        [Test]
        public void DecommissionAtTest()
        {
            // TODO unit test for the property 'DecommissionAt'
        }
        /// <summary>
        /// Test the property 'Diversity'
        /// </summary>
        [Test]
        public void DiversityTest()
        {
            // TODO unit test for the property 'Diversity'
        }
        /// <summary>
        /// Test the property 'ExternalRef'
        /// </summary>
        [Test]
        public void ExternalRefTest()
        {
            // TODO unit test for the property 'ExternalRef'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ManagingAccount'
        /// </summary>
        [Test]
        public void ManagingAccountTest()
        {
            // TODO unit test for the property 'ManagingAccount'
        }
        /// <summary>
        /// Test the property 'NscRequiredContactRoles'
        /// </summary>
        [Test]
        public void NscRequiredContactRolesTest()
        {
            // TODO unit test for the property 'NscRequiredContactRoles'
        }
        /// <summary>
        /// Test the property 'ProductOffering'
        /// </summary>
        [Test]
        public void ProductOfferingTest()
        {
            // TODO unit test for the property 'ProductOffering'
        }
        /// <summary>
        /// Test the property 'ProviderRef'
        /// </summary>
        [Test]
        public void ProviderRefTest()
        {
            // TODO unit test for the property 'ProviderRef'
        }
        /// <summary>
        /// Test the property 'PurchaseOrder'
        /// </summary>
        [Test]
        public void PurchaseOrderTest()
        {
            // TODO unit test for the property 'PurchaseOrder'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
