/* 
 * IX-API
 *
 *  This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error. 
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VLanConfigDot1QPartial
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VLanConfigDot1QPartialTests
    {
        // TODO uncomment below to declare an instance variable for VLanConfigDot1QPartial
        //private VLanConfigDot1QPartial instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VLanConfigDot1QPartial
            //instance = new VLanConfigDot1QPartial();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VLanConfigDot1QPartial
        /// </summary>
        [Test]
        public void VLanConfigDot1QPartialInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VLanConfigDot1QPartial
            //Assert.IsInstanceOfType<VLanConfigDot1QPartial> (instance, "variable 'instance' is a VLanConfigDot1QPartial");
        }


        /// <summary>
        /// Test the property 'Vlan'
        /// </summary>
        [Test]
        public void VlanTest()
        {
            // TODO unit test for the property 'Vlan'
        }
        /// <summary>
        /// Test the property 'VlanEthertype'
        /// </summary>
        [Test]
        public void VlanEthertypeTest()
        {
            // TODO unit test for the property 'VlanEthertype'
        }
        /// <summary>
        /// Test the property 'VlanType'
        /// </summary>
        [Test]
        public void VlanTypeTest()
        {
            // TODO unit test for the property 'VlanType'
        }

    }

}
