# coding: utf-8

"""
    IX-API

     This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error.   # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v_lan_config_dot1_q_partial import VLanConfigDot1QPartial  # noqa: E501
from swagger_client.rest import ApiException


class TestVLanConfigDot1QPartial(unittest.TestCase):
    """VLanConfigDot1QPartial unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVLanConfigDot1QPartial(self):
        """Test VLanConfigDot1QPartial"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v_lan_config_dot1_q_partial.VLanConfigDot1QPartial()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
