# coding: utf-8

"""
    IX-API

     This API allows to config/change/delete Internet Exchange services.  # Filters  When querying collections, the provided query parameters are validated. Unknown query parameters are ignored. Providing invalid filter values should yield a validation error.   # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.mp2_mp_network_service import MP2MPNetworkService  # noqa: E501
from swagger_client.rest import ApiException


class TestMP2MPNetworkService(unittest.TestCase):
    """MP2MPNetworkService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMP2MPNetworkService(self):
        """Test MP2MPNetworkService"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.mp2_mp_network_service.MP2MPNetworkService()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
