# coding: utf-8

"""
    IX-API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.lizard import Lizard  # noqa: E501
from swagger_client.rest import ApiException


class TestLizard(unittest.TestCase):
    """Lizard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLizard(self):
        """Test Lizard"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.lizard.Lizard()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
