/* 
 * IX-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Lizard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LizardTests
    {
        // TODO uncomment below to declare an instance variable for Lizard
        //private Lizard instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Lizard
            //instance = new Lizard();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Lizard
        /// </summary>
        [Test]
        public void LizardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Lizard
            //Assert.IsInstanceOfType<Lizard> (instance, "variable 'instance' is a Lizard");
        }


        /// <summary>
        /// Test the property 'LovesRocks'
        /// </summary>
        [Test]
        public void LovesRocksTest()
        {
            // TODO unit test for the property 'LovesRocks'
        }

    }

}
